name: Daily Energy Update

on:
  schedule:
    - cron: '0 6 * * *'
  workflow_dispatch:

jobs:
  update_db:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: List files for debug
        run: ls -la

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r ./requirements.txt

      - name: Run daily update
        run: python ./daily_update.py
